### ISSUE TITLE
Environment variable to enable/disable.

### ISSUE THREAD

**Issue by frederikhors** [catcombo/go-staticfiles#3]
I think we can add an env var to enable/disable staticfiles.

Particularly useful for development vs production.

Something like: `STATIC_FILES_ENABLED=true/false`.

What do you think?

**Comment by catcombo** [comment]
Good idea. Need a time to implement it in the best way.

**Comment by catcombo** [comment]
Take a look the PR. I've updated [README](https://github.com/catcombo/go-staticfiles/blob/feature/add-debug-mode/README.md) and propose to use `storage.Debug = true` to enable debug mode.

**Comment by frederikhors** [comment]
I think it's ok. But I would call that variable differently instead of `Debug`. Maybe `Development`?

**Comment by catcombo** [comment]
I based on names from [Django](https://docs.djangoproject.com/en/2.2/ref/settings/#std:setting-DEBUG). But perhaps you may find analogies of debug mode from other libraries in Go to compare with.

**Comment by frederikhors** [comment]
I think it is confusing.

But it's just my opinion. You are the author and you are also a great author.

**Comment by catcombo** [comment]
I think you're right. It's confusing and must be named more specific. But `Development` is too common in my view. Maybe it should be named `storage.Enabled = true/false`. What do you think?

**Comment by frederikhors** [comment]
> I think you're right. It's confusing and must be named more specific. But `Development` is too common in my view. Maybe it should be named `storage.Enabled = true/false`. What do you think?

Yes. In my projects I already named it `STATICFILES_ENABLED`. So it's a yes for me.

**Comment by frederikhors** [comment]
Please release so I can try now.

**Comment by catcombo** [comment]
Sure, but I need to make a few cosmetic changes to the code first.

**Comment by catcombo** [comment]
Released in [v0.2.0](https://github.com/catcombo/go-staticfiles/releases/tag/v0.2.0)
