### ISSUE TITLE
How to exclude some files/folder?

### ISSUE THREAD

**Issue by frederikhors** [catcombo/go-staticfiles#7]
Is there already a way to exclude some files/folder?

**Comment by catcombo** [comment]
I think the best option is to move unexported assets to a separate directory (e.g. static/public and static/private).

**Comment by frederikhors** [comment]
Oh no, please no.

Can we use in someway a glob utility?

**Comment by catcombo** [comment]
Ok, I'll think how to implement it.

**Comment by catcombo** [comment]
@frederikhors check the PR and tell what you think about it please.

**Comment by frederikhors** [comment]
It looks good to me.

**Comment by catcombo** [comment]
Good! Released in v0.4.0.
